services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    
networks:
  default:
    name: apie_default
